name: rondas
description: "Sistema de Control de Rondas de Seguridad Móvil (Flutter Web / Android APK)"
publish_to: 'none'
version: 1.4.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  geolocator: ^12.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.0
  audioplayers: ^6.0.0
  battery_plus: ^6.0.0
  mobile_scanner: ^7.4.0
  flutter_nfc_kit: ^3.6.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  safe_device: ^1.4.1
  image_picker: ^1.2.3
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  flutter_local_notifications: ^22.2.0
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
